version: "3"
services:
    php72: &latest
        image: anax/dev:php72
        ports:
            - "10072:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    latest:
        <<: *latest
    php71:
        image: anax/dev:php71
        ports:
            - "10071:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    php70:
        image: anax/dev:php70
        ports:
            - "10070:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    php56:
        image: anax/dev:php56
        ports:
            - "10056:80"
        volumes:
            - .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
